import Hero from '@/components/Hero';
import Library from '@/components/Library';
import type { SkillSummary } from '@/lib/types';
// Generated by scripts/build-skills.ts (prebuild/predev) — slug + card metadata
// only, no file contents, so the static HTML stays small.
import skillsIndex from '@/lib/skills-index.json';

export default function HomePage() {
  const skills = skillsIndex as SkillSummary[];
  return (
    <>
      <Hero />
      <Library skills={skills} />
    </>
  );
}
